### ISSUE TITLE
你们每人1W+的代码怎么来的?

### ISSUE THREAD

**Issue by mayli** [wkl/chain-replication#1]
![screen shot 2015-07-17 at 5 06 09 pm](https://cloud.githubusercontent.com/assets/822628/8759310/25e95dde-2ca6-11e5-9605-ac6fb81d0e97.png)

**Comment by mayli** [comment]
FreeBSD 10 ...

**Comment by wkl** [comment]
config/*.json? @rainystar

**Comment by rainystar** [comment]
protobuf生成+我傍大腿

**Comment by rainystar** [comment]
protobuf生成+我傍的大腿牛逼

**Comment by mayli** [comment]
DIAO

**Comment by wkl** [comment]
4000 lines for phase 3: https://github.com/wkl/chain-replication/blob/phase3/README.txt#L109
